import type { Metadata } from "next";
import "./globals.css";

import { Plus_Jakarta_Sans } from 'next/font/google';

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-plus-jakarta-sans',
});



export const metadata: Metadata = {
  title: "Morent-Car-App",
  description: "Generated by create next app",
 icons:{
  icon:"/images/favicon.ico",
 },

};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={plusJakartaSans.variable}>
      <body className={plusJakartaSans.className}>{children}</body>
    </html>
  );
}


